# Generated by Django 5.0.4 on 2024-04-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
            ],
            options={
                'db_table': 'egg_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('damage_class_id', models.IntegerField(blank=True, null=True)),
                ('identifier', models.CharField(max_length=79)),
                ('is_battle_only', models.IntegerField()),
                ('game_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
                ('generation_id', models.IntegerField()),
                ('damage_class_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'types',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EggGroup',
        ),
        migrations.DeleteModel(
            name='pokemon_types',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='move',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemonegggroups',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemonformgenerations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemonmoves',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemonstats',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pokemontypes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
